baseURL = 'https://DaniloHorn.github.io/'
languageCode = 'en-us'
title = 'Strays in need Serbia'
theme = 'ananke'

[[menu.main]]
name = "ğŸ¾ Adoptieren"
url = "/adoptieren/"
weight = 2

[[menu.main]]
name = "ğŸ§‘â€ğŸ¤â€ğŸ§‘ Mitglied werden"
url = "/mitglied-werden/"
weight = 3

[[menu.main]]
name = "ğŸ“° News"
url = "/news/"
weight = 5

[[menu.main]]
name = "ğŸ’– Spenden"
url = "/spenden/"
weight = 1

[[menu.main]]
name = "ğŸ  Unser Verein"
url = "/unser-verein/"
weight = 4

[params]
  logo = "/images/strays-in-need-serbia.svg"
  footer_text = "Strays in Need â€“ Gemeinsam fÃ¼r eine bessere Zukunft fÃ¼r Tiere."